name: Build and Deploy
on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install
        run: |
          yarn install

      - name: Lint
        run: |
          yarn run lint

      - name: Build
        run: |
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
